linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"

sudo: required
services:
  - docker
env:
  - ADDON="dasshio"
script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - python .ci/build.py